import os

SYMBOLS = {"AAPL", "MSFT", "NVDA", "GOOGL", "AMZN", "META", "TSLA", "AMD", "AVGO", "PLTR"}

AWS_REGION = os.environ["AWS_REGION"]
KINESIS_STREAM_RAW_TRADES = os.environ["KINESIS_STREAM_RAW_TRADES"]
KINESIS_STREAM_PROCESSED = os.environ["KINESIS_STREAM_PROCESSED"]
S3_BUCKET_RAW = os.environ["S3_BUCKET_RAW"]
SAGEMAKER_ENDPOINT_NAME = os.environ["SAGEMAKER_ENDPOINT_NAME"]

# Volume detector
VOLUME_WINDOW_SECS = 300
VOLUME_MIN_WINDOW_SECS = 60
VOLUME_SPIKE_MULTIPLIER = 4.0
VOLUME_COOLDOWN_SECS = 180

# Momentum detector
MOMENTUM_CANDLE_WINDOW = 5
MOMENTUM_MIN_AGREE = 3
MOMENTUM_COOLDOWN_SECS = 120

# Volatility detector
VOLATILITY_WINDOW_SECS = 300
VOLATILITY_MIN_WINDOW_SECS = 60
VOLATILITY_Z_THRESHOLD = 2.5
VOLATILITY_COOLDOWN_SECS = 120

# Sector detector
SECTOR_SNAPSHOT_INTERVAL_SECS = 60
SECTOR_STALE_SECS = 120

# Warm-start reads back max(volume_window, volatility_window) = 300s
WARM_START_LOOKBACK_MS = max(VOLUME_WINDOW_SECS, VOLATILITY_WINDOW_SECS) * 1000
